[package]
name = "yt-dlp-cool"
version = "3.1.6"
description = "A modern YouTube Downloader based on yt-dlp and Tauri"
authors = ["zhaoxiaofeng"]
license = "MIT"
edition = "2021"

[lib]
name = "ytdl_flow_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
regex = "1"
uuid = { version = "1", features = ["v4", "serde"] }
anyhow = "1"
url = "2.5.7"
winreg = "0.52"
encoding_rs = "0.8.35"
sha2 = "0.10.9"
tempfile = "3.27.0"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-notification = "2"
tauri-plugin-store = "2"
tauri-plugin-updater = "2.13.0"
tauri-plugin-process = "2.4.0"
tauri-plugin-single-instance = "2.5.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_JobObjects", "Win32_Security"] }
